version: '3'
services:
  web:
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    depends_on:
      - db-mysql
      - redis
    networks: 
      - network-app
  db-mysql:
    image: mysql:5.7.22
    restart: always
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - "./.docker/dbdata:/var/lib/postgresql/data"
    networks: 
      - network-app
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    networks: 
      - network-app
    depends_on:
      - web

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks: 
      - network-app
networks: 
  network-app:
